version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 fc25_denoise.asgi:application
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  redis_data:
  media:
  static:
