# Generated by Django 4.2.6 on 2025-11-08 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0003_vocalseparationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBoostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='uploads/audio_boost/original/')),
                ('boosted_file', models.FileField(blank=True, null=True, upload_to='uploads/audio_boost/boosted/')),
                ('boost_level', models.CharField(choices=[('gentle', 'Gentle'), ('medium', 'Medium'), ('strong', 'Strong')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_boost_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
