# Generated by Django 4.2.6 on 2025-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_audioboostfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedaudiofile',
            name='model_type',
            field=models.CharField(choices=[('deepfilternet2', 'DeepFilterNet2'), ('deepfilternet3', 'DeepFilterNet3')], default='deepfilternet2', max_length=20),
        ),
    ]
