# Generated by Django 4.2.6 on 2025-11-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_uploadedaudiofile_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedaudiofile',
            name='model_type',
        ),
    ]
