# Generated by Django 4.2.6 on 2025-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_remove_model_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioboostfile',
            name='boost_level',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('medium', 'Medium'), ('strong', 'Strong'), ('max', 'Maximum')], default='medium', max_length=20),
        ),
    ]
