# Generated by Django 4.2.6 on 2025-11-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0008_add_boost_to_denoise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerExtractionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('target_speaker_filename', models.CharField(max_length=255)),
                ('conversation_file', models.FileField(upload_to='uploads/speaker_extraction/conversations/')),
                ('target_speaker_file', models.FileField(upload_to='uploads/speaker_extraction/targets/')),
                ('extracted_file', models.FileField(blank=True, null=True, upload_to='uploads/speaker_extraction/extracted/')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_extraction_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
