# Generated by Django 4.2.6 on 2025-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0009_speakerextractionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerextractionfile',
            name='boost_level',
            field=models.CharField(choices=[('none', 'No Boost'), ('2x', '2x Volume'), ('3x', '3x Volume'), ('4x', '4x Volume'), ('5x', '5x Volume')], default='none', max_length=10),
        ),
    ]
