# Generated by Django 4.2.6 on 2025-11-19 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0010_speakerextractionfile_boost_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCloneFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('target_voice_filename', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='uploads/voice_clone/source/')),
                ('target_voice_file', models.FileField(upload_to='uploads/voice_clone/target/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='uploads/voice_clone/converted/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_clone_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
